### ISSUE TITLE
fatal error: 'QAudioInput' file not found

### ISSUE THREAD

**Issue by shayanb** [ieatlint/MagRead#16]
On Mac OS X 10.9.5 I get this error while trying to run 'make':

```
In file included from magread.cpp:20:
./magread.h:37:10: fatal error: 'QAudioInput' file not found
#include <QAudioInput>
         ^
1 error generated.
make: *** [magread.o] Error 1
```

**Comment by ieatlint** [comment]
This code was written for Qt 4.6.4, and will require some configuration changes for later versions of Qt.  At present, this code is considered finished, so I won't be contributing any updates due to changes to Qt.

**Comment by shayanb** [comment]
I've installed Qt 4.6.4 but same issue.
